--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.3.9.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 4/11/2023 1:24:14 PM
-- Server version: 15.00.2101
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE QuizProject
GO

IF DB_NAME() <> N'QuizProject' SET NOEXEC ON
GO

--
-- Create table [dbo].[Questions]
--
PRINT (N'Create table [dbo].[Questions]')
GO
CREATE TABLE dbo.Questions (
  QuestionId uniqueidentifier NOT NULL,
  CategoryId uniqueidentifier NOT NULL,
  QuestionCode varchar(50) NOT NULL,
  QuestionName varchar(200) NOT NULL,
  ChoicesId uniqueidentifier NOT NULL,
  CONSTRAINT PK_Questions_QuestionId PRIMARY KEY CLUSTERED (QuestionId)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[QuestionChoices]
--
PRINT (N'Create table [dbo].[QuestionChoices]')
GO
CREATE TABLE dbo.QuestionChoices (
  ChoiceId uniqueidentifier NOT NULL,
  QuestionId uniqueidentifier NULL,
  IsCorrect bit NULL,
  ChoiceText varchar(50) NULL,
  ChoiceImage varbinary(max) NULL,
  CONSTRAINT PK_QuestionChoices_ChoiceId PRIMARY KEY CLUSTERED (ChoiceId)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Categories]
--
PRINT (N'Create table [dbo].[Categories]')
GO
CREATE TABLE dbo.Categories (
  CategoryId uniqueidentifier NOT NULL,
  CategoryName varchar(50) NOT NULL,
  CategoryInfo varchar(200) NULL,
  CONSTRAINT PK_Categories_CategoryId PRIMARY KEY CLUSTERED (CategoryId)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[CategoryRelationship]
--
PRINT (N'Create table [dbo].[CategoryRelationship]')
GO
CREATE TABLE dbo.CategoryRelationship (
  CategoryParentId uniqueidentifier NOT NULL,
  CategoryChildId uniqueidentifier NOT NULL,
  CONSTRAINT PK_CategoryRelationship PRIMARY KEY CLUSTERED (CategoryParentId, CategoryChildId)
)
ON [PRIMARY]
GO

--
-- Create index [KEY_CategoryRelationship_Categ] on table [dbo].[CategoryRelationship]
--
PRINT (N'Create index [KEY_CategoryRelationship_Categ] on table [dbo].[CategoryRelationship]')
GO
CREATE UNIQUE INDEX KEY_CategoryRelationship_Categ
  ON dbo.CategoryRelationship (CategoryParentId)
  ON [PRIMARY]
GO

-- 
-- Dumping data for table Questions
--
PRINT (N'Dumping data for table Questions')
-- Table QuizProject.dbo.Questions does not contain any data (it is empty)

-- 
-- Dumping data for table QuestionChoices
--
PRINT (N'Dumping data for table QuestionChoices')
-- Table QuizProject.dbo.QuestionChoices does not contain any data (it is empty)

-- 
-- Dumping data for table CategoryRelationship
--
PRINT (N'Dumping data for table CategoryRelationship')
-- Table QuizProject.dbo.CategoryRelationship does not contain any data (it is empty)

-- 
-- Dumping data for table Categories
--
PRINT (N'Dumping data for table Categories')
INSERT dbo.Categories VALUES ('9b2c338a-8977-435e-b2ab-ec67f20492ba', 'IT', 'Demo')
GO

USE QuizProject
GO

IF DB_NAME() <> N'QuizProject' SET NOEXEC ON
GO

--
-- Create foreign key [FK_Questions_CategoryId] on table [dbo].[Questions]
--
PRINT (N'Create foreign key [FK_Questions_CategoryId] on table [dbo].[Questions]')
GO
ALTER TABLE dbo.Questions
  ADD CONSTRAINT FK_Questions_CategoryId FOREIGN KEY (CategoryId) REFERENCES dbo.Categories (CategoryId)
GO

--
-- Create foreign key [FK_QuestionChoices_QuestionId] on table [dbo].[QuestionChoices]
--
PRINT (N'Create foreign key [FK_QuestionChoices_QuestionId] on table [dbo].[QuestionChoices]')
GO
ALTER TABLE dbo.QuestionChoices
  ADD CONSTRAINT FK_QuestionChoices_QuestionId FOREIGN KEY (QuestionId) REFERENCES dbo.Questions (QuestionId)
GO

--
-- Create foreign key [FK_CategoryRelationship_CategoryParentId] on table [dbo].[CategoryRelationship]
--
PRINT (N'Create foreign key [FK_CategoryRelationship_CategoryParentId] on table [dbo].[CategoryRelationship]')
GO
ALTER TABLE dbo.CategoryRelationship
  ADD CONSTRAINT FK_CategoryRelationship_CategoryParentId FOREIGN KEY (CategoryParentId) REFERENCES dbo.Categories (CategoryId)
GO
SET NOEXEC OFF
GO